### ISSUE TITLE
Negative outside temp turning into >6550 C?

### ISSUE THREAD

**Issue by Kosta-Github** [OStrama/weishaupt_modbus#56]
**Describe the bug**

It looks like the outside temp is broken.

It could be that negative values are turning into +6550 C?

See: 
![IMG_0307](https://github.com/user-attachments/assets/5e7978c7-ca3f-4ca1-9b53-2e9567efa635)

![IMG_0308](https://github.com/user-attachments/assets/75e92516-095c-4263-acfd-1a6ee9c11877)

Latest version of WBB.

**Comment by OStrama** [comment]
This should have been fixed in earlier version.
I released 1.0.4 some minutes ago. Please read readme before installation..

**Comment by OStrama** [comment]
Checked it, on 1.0.4 it shows the right value:
<img width="414" alt="image" src="https://github.com/user-attachments/assets/9b27eacc-7b1c-4906-80af-2d154da3e1db">

**Comment by kowi-k** [comment]
I still have this issue but for “Ansaugtemperatur“ & in rare cases for outside temperature as well. 
(1.0.6)

![Image](https://github.com/user-attachments/assets/3886dd94-773a-4097-8dfe-491ec61f5543)

**Comment by MadOne** [comment]
This is a different error because the temperature did not go below 0 in your case.
This looks like a sensor / controller error to me.

**Comment by OStrama** [comment]
could you track these sensors in WEM portal?
I aggree with MadOne: The negative value issue is fixed since soome versions and I also had a lot of negative outside temperatures the last days and at least on my installation it looks O.K.
Did you really install the latest verson? Could you uninstall the integration and delete the files in the integration's sub directory completely before re-installing it?

**Comment by kowi-k** [comment]
I will try re-installing. The sensors from the WEM portal are working fine.
